import { configureStore } from "@reduxjs/toolkit";
import studentApi from "./studentApi";

const store = configureStore({
    reducer: {
        // studentApi.reducer: reducer automatically generated by RTKQ
        [studentApi.reducerPath] : studentApi.reducer,
    },
    middleware: getDefaultMiddleware => {
        return getDefaultMiddleware().concat(studentApi.middleware);
    },
});

export default store;
